#!/bin/bash

GOOGLE_APPLICATION_CREDENTIALS_PATH=/tmp/credentials

if [ ! -f "$GOOGLE_APPLICATION_CREDENTIALS" ]; then
  echo "$GOOGLE_APPLICATION_CREDENTIALS" > "$GOOGLE_APPLICATION_CREDENTIALS_PATH"
  export GOOGLE_APPLICATION_CREDENTIALS="$GOOGLE_APPLICATION_CREDENTIALS_PATH"
fi

exec "$@"
